# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOCTYPE', models.CharField(max_length=128)),
                ('AN', models.CharField(max_length=128, unique=True)),
                ('WORDCOUNT', models.IntegerField()),
                ('DATE', models.DateTimeField()),
                ('HEADLINE', models.CharField(max_length=128)),
                ('CATEGORY', models.CharField(max_length=128)),
                ('AUTHOR', models.CharField(max_length=128)),
                ('NEWSITE', models.CharField(max_length=128)),
                ('folder', models.CharField(max_length=128)),
                ('LEADPARA', models.CharField(max_length=128)),
                ('TAILPARAS', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
