# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180504_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='an',
            new_name='AN',
        ),
    ]
