# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180504_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='folder',
        ),
        migrations.AddField(
            model_name='article',
            name='FOLDER',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='AUTHOR',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='CATEGORY',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='LEADPARA',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='NEWSITE',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='TAILPARAS',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='WORDCOUNT',
            field=models.IntegerField(null=True),
        ),
    ]
