# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_articleraw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleRaw',
        ),
    ]
